AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Fargate deployment for BookLendingService API

Parameters:
  ImageUrl:
    Type: String
    Description: "Full ECR image URL (e.g., 123456789012.dkr.ecr.eu-west-1.amazonaws.com/booklendingservice:latest)"

  SubnetId1:
    Type: String
    Description: "Public subnet 1 ID"

  SubnetId2:
    Type: String
    Description: "Public subnet 2 ID"

  SecurityGroupId:
    Type: String
    Description: "Security group ID allowing HTTP (port 80)"

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: BookLendingServiceCluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BookLendingServiceExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/BookLendingService
      RetentionInDays: 14

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: BookLendingServiceTask
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref TaskExecutionRole
      ContainerDefinitions:
        - Name: BookLendingService
          Image: !Ref ImageUrl
          Essential: true
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: /ecs/BookLendingService
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command: ["CMD-SHELL", "curl -f http://localhost:80/ || exit 1"]
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 10

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      ServiceName: BookLendingServiceService
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetId1
            - !Ref SubnetId2
          SecurityGroups:
            - !Ref SecurityGroupId

Outputs:
  ClusterName:
    Value: !Ref ECSCluster

  ServiceName:
    Value: !Ref ECSService

  TaskDefinitionArn:
    Value: !Ref TaskDefinition
